In [2]:
import pandas as pd
import numpy as np
import gradio as gr
import plotly.graph_objects as go
from plotly.colors import n_colors
from datetime import datetime

In [3]:

df1 = pd.read_csv(
    r"D:\Win-Factor98\df1_cleaned.csv",
    low_memory=False,
    parse_dates=['start_date']
)

dfx = pd.read_csv(
    r"D:\Win-Factor98\dfx.csv",
    low_memory=False,parse_dates=['start_date']
)

In [4]:
df1

,player_id,start_date,fantasy_score_total,player_team_str,opposition_team_str,player_role_encoded,fantasy_score_total_predicted_stacked,credit,player_name,runs_scored,...,lbw_done,maidens,dot_balls_as_bowler,player_team,opposition_team,all_rounder_score,fielding,batting_impact,bowling_impact,final_roles
0,4841,2023-02-01,58,South Africa,England,1,54.607219,7.0,AK Markram,39,...,0,0,10,280,92,8.666667,5,0.138889,0.400000,All-rounder
1,9830,2023-02-01,20,South Africa,England,1,47.869423,6.0,DA Miller,13,...,0,0,0,280,92,2.888889,0,0.428571,0.000000,Batsman
2,6213,2023-02-01,85,MI Emirates,Gulf Giants,2,44.033109,7.0,DJ Bravo,3,...,0,0,11,185,117,14.666667,14,0.000000,0.653846,Bowler
3,1548,2023-02-01,131,South Africa,England,4,49.073455,8.0,H Klaasen,80,...,0,0,0,280,92,17.777778,15,0.174603,0.000000,Wicketkeeper
4,10684,2023-02-01,27,MI Emirates,Gulf Giants,2,39.325074,6.0,Fazalhaq Farooqi,0,...,0,0,9,185,117,7.000000,0,0.000000,0.500000,Bowler
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118961,270,2025-05-20,10,Nepal,Thailand,1,18.677247,6.0,Roma Thapa,0,...,0,0,0,213,318,0.000000,5,0.000000,0.000000,Batsman
118962,471,2025-05-20,58,Somerset,The Blaze,2,37.166177,7.0,OJ Barnes,0,...,0,0,18,279,319,14.000000,0,0.000000,0.428571,Bowler
118963,3395,2025-05-20,51,Nepal,Thailand,1,26.941447,7.0,R Airee,20,...,0,0,4,213,318,11.444444,0,0.071429,0.368421,Bowler
118964,3432,2025-05-20,91,Rajasthan Royals,Chennai Super Kings,2,36.793087,7.0,Akash Madhwal,0,...,0,0,9,252,51,21.000000,0,0.000000,0.720000,Bowler
118965,7455,2025-05-20,33,Somerset,The Blaze,1,33.486028,6.0,FC Wilson,28,...,0,0,0,279,319,6.222222,0,0.166667,0.000000,Batsman

In [24]:
dfx

,player_id,match_id,start_date,player_name,runs_scored,player_out,balls_faced,fours_scored,sixes_scored,catches_taken,...,fantasy_score_batting,fantasy_score_bowling,fantasy_score_total,all_rounder_score,fielding,batting_impact,bowling_impact,match_type_code,player_role_encoded,final_role
0,922,1158348,2018-08-21,M King,10,1,30,1,0,1,...,5,8,17,2.222222,5,0.033333,0.0,0.0,1,Batsman
1,922,1182644,2019-05-05,M King,8,1,18,1,0,0,...,3,0,7,1.777778,0,0.055556,0.0,0.0,1,Batsman
2,922,1275107,2021-09-09,M King,1,0,5,0,0,0,...,1,0,5,0.222222,0,0.000000,0.0,0.0,1,Batsman
3,922,1275113,2021-09-15,M King,0,0,0,0,0,0,...,0,0,4,0.000000,0,0.000000,0.0,0.0,1,Batsman
4,922,1275125,2021-09-14,M King,1,1,15,0,0,0,...,-5,0,-1,0.222222,0,0.000000,0.0,0.0,1,Batsman
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416707,11770,1473475,2025-04-20,Naman Dhir,0,0,0,0,0,0,...,0,0,4,0.000000,0,0.000000,0.0,0.0,1,Batsman
416708,11770,1473478,2025-04-23,Naman Dhir,0,0,0,0,0,1,...,0,8,12,0.000000,5,0.000000,0.0,0.0,1,Batsman
416709,11770,1473482,2025-04-27,Naman Dhir,25,0,13,2,2,1,...,37,8,49,5.555556,5,0.461538,0.0,0.0,1,Batsman
416710,11770,1473487,2025-05-01,Naman Dhir,0,0,0,0,0,0,...,0,0,4,0.000000,0,0.000000,0.0,0.0,1,Batsman
416711,11770,1473493,2025-05-06,Naman Dhir,7,1,10,1,0,1,...,6,8,18,1.555556,5,0.100000,0.0,0.0,1,Batsman

C:\Users\abhau\AppData\Local\Temp\ipykernel_34140\86106552.py:159: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

In [5]:
dfx.columns

Index(['player_id', 'match_id', 'start_date', 'player_name', 'runs_scored',
       'player_out', 'balls_faced', 'fours_scored', 'sixes_scored',
       'catches_taken', 'run_out_direct', 'run_out_throw', 'stumpings_done',
       'out_kind', 'dot_balls_as_batsman', 'order_seen', 'balls_bowled',
       'runs_conceded', 'wickets_taken', 'bowled_done', 'lbw_done', 'maidens',
       'dot_balls_as_bowler', 'player_team', 'opposition_team',
       'fantasy_score_batting', 'fantasy_score_bowling', 'fantasy_score_total',
       'all_rounder_score', 'fielding', 'batting_impact', 'bowling_impact',
       'match_type_code', 'player_role_encoded', 'final_role'],
      dtype='object')

In [6]:
df1.columns

Index(['player_id', 'start_date', 'fantasy_score_total', 'player_team_str',
       'opposition_team_str', 'player_role_encoded',
       'fantasy_score_total_predicted_stacked', 'credit', 'player_name',
       'runs_scored', 'player_out', 'balls_faced', 'fours_scored',
       'sixes_scored', 'catches_taken', 'run_out_direct', 'run_out_throw',
       'stumpings_done', 'out_kind', 'dot_balls_as_batsman', 'balls_bowled',
       'runs_conceded', 'wickets_taken', 'bowled_done', 'lbw_done', 'maidens',
       'dot_balls_as_bowler', 'player_team', 'opposition_team',
       'all_rounder_score', 'fielding', 'batting_impact', 'bowling_impact',
       'final_roles'],
      dtype='object')

In [ ]:
import pandas as pd
import numpy as np
import gradio as gr
import plotly.graph_objects as go
from plotly.colors import n_colors
from datetime import datetime

df1['start_date'] = pd.to_datetime(df1['start_date'])

if 'player_name' not in df1.columns and 'name_x' in df1.columns:
    df1.rename(columns={'name_x': 'player_name'}, inplace=True)


if 'final_roles' in df1.columns and 'final_role' not in df1.columns:
    df1.rename(columns={'final_roles': 'final_role'}, inplace=True)

if 'player_team_str' not in df1.columns and 'team' in df1.columns:
    df1.rename(columns={'team': 'player_team_str'}, inplace=True)

for col in ['runs_scored', 'balls_faced', 'wickets_taken', 'runs_conceded', 'balls_bowled',
            'fantasy_score_total', 'fantasy_score_total_predicted_stacked', 'fours_scored', 'sixes_scored']:
    if col not in df1.columns:
        df1[col] = 0
        
dfx = dfx.copy()

# Using weighted stacked fantasy score
weights = np.array([0.51, 0.19, 0.14, 0.12, 0.1, 0.08, 0.06])
weights = weights / weights.sum()

def get_career_stats_for_player(player_name, dfx):
    """
    Returns a markdown string summarizing career stats for player_name using dataframe dfx.
    Always returns a single string (no tuple).
    """
    player_df = dfx[dfx['player_name'] == player_name]
    if player_df.empty:
        return f"### {player_name}\nNo career data available for this player."

    # Batting stats
    batting = player_df[player_df['final_role'].isin(['Batsman', 'Wicketkeeper', 'All-rounder'])]
    total_matches = len(player_df['start_date'].unique())
    total_runs = batting['runs_scored'].sum()
    total_balls = batting['balls_faced'].sum()
    total_fifties = ((batting['runs_scored'] >= 50) & (batting['runs_scored'] < 100)).sum()
    total_hundreds = (batting['runs_scored'] >= 100).sum()
    batting_avg = (total_runs / total_matches) if total_matches > 0 else 0
    strike_rate_bat = (total_runs / total_balls * 100) if total_balls > 0 else 0

    # Bowling stats
    bowling = player_df[player_df['final_role'].isin(['Bowler', 'All-rounder'])]
    total_wickets = bowling['wickets_taken'].sum() if 'wickets_taken' in bowling.columns else 0
    total_runs_conceded = bowling['runs_conceded'].sum() if 'runs_conceded' in bowling.columns else 0
    total_balls_bowled = bowling['balls_bowled'].sum() if 'balls_bowled' in bowling.columns else 0
    total_fifers = (bowling['wickets_taken'] >= 5).sum() if 'wickets_taken' in bowling.columns else 0
    bowling_avg = (total_runs_conceded / total_wickets) if total_wickets > 0 else 0
    economy = (total_runs_conceded / (total_balls_bowled / 6)) if total_balls_bowled > 0 else 0
    strike_rate_bowl = (total_balls_bowled / total_wickets) if total_wickets > 0 else 0

    role = player_df['final_role'].mode()[0] if not player_df['final_role'].empty else "Unknown"

    # Format career stats string depending on role
    if role in ['Batsman', 'Wicketkeeper']:
        stats_str = f"""### {player_name} — {role}

- Matches: {total_matches}
- Runs: {total_runs}
- Batting Average: {batting_avg:.2f}
- Strike Rate: {strike_rate_bat:.2f}
- 50s: {total_fifties}
- 100s: {total_hundreds}
"""
    elif role == 'Bowler':
        stats_str = f"""### {player_name} — {role}

- Matches: {total_matches}
- Wickets: {total_wickets}
- Bowling Average: {bowling_avg:.2f}
- Economy Rate: {economy:.2f}
- Strike Rate: {strike_rate_bowl:.2f}
- Fifers: {total_fifers}
"""
    elif role == 'All-rounder':
        stats_str = f"""### {player_name} — {role}

- Matches: {total_matches}

**Batting:**
- Runs: {total_runs}
- Batting Average: {batting_avg:.2f}
- Strike Rate: {strike_rate_bat:.2f}
- 50s: {total_fifties}
- 100s: {total_hundreds}

**Bowling:**
- Wickets: {total_wickets}
- Bowling Average: {bowling_avg:.2f}
- Economy Rate: {economy:.2f}
- Strike Rate: {strike_rate_bowl:.2f}
- Fifers: {total_fifers}
"""
    else:
        stats_str = f"### {player_name}\nNo detailed career stats available."

    return stats_str

# Predict Top11 Function 
def predict_top11(selected_players, match_date_str):
    """
    Takes selected_players (list) and match_date_str (YYYY-MM-DD).
    Returns: status_text, updated_player_dropdown_choices (gr.update), fig
    """
    if not selected_players or len(selected_players) < 11:
        return "Please select at least 11 players.", gr.update(choices=[]), None

    try:
        match_date = pd.to_datetime(match_date_str)
    except Exception:
        return "Invalid match date format. Use YYYY-MM-DD.", gr.update(choices=selected_players), None

    df_selected = df1[df1['player_name'].isin(selected_players)]
    df_hist = df_selected[df_selected['start_date'] < match_date]

    if df_hist.empty:
        return "No historical data available.", gr.update(choices=selected_players), None

    # Keep last 7 matches per player
    df_hist = df_hist.sort_values('start_date', ascending=False)
    df_hist = df_hist.groupby('player_id').head(7)

    # Compute score per player
    def compute_score(g):
        scores = g['fantasy_score_total_predicted_stacked'].fillna(0).values
        w = weights[:len(scores)]
        if len(w) < len(scores):
            w = np.pad(w, (0, len(scores) - len(w)), 'constant')
        player_id = g['player_id'].iloc[0]
        player_name = g['player_name'].iloc[0]
        final_role_mode = g['final_role'].mode()
        final_role = final_role_mode[0] if not final_role_mode.empty else 'Batsman'
        player_team = g['player_team_str'].iloc[0] if 'player_team_str' in g.columns else ''
        score_val = 0
        if len(scores) > 0:
            try:
                score_val = (np.dot(scores, w) ** 1.15) - np.std(scores) * 1.095
            except Exception:
                score_val = float(np.nan)
        return pd.Series({
            'player_id': player_id,
            'player_name': player_name,
            'final_role': final_role,
            'player_team': player_team,
            'score': score_val
        })

    result = df_hist.groupby('player_id').apply(compute_score).reset_index(drop=True)

    if len(result) < 11:
        return "Less than 11 players have data.", gr.update(choices=selected_players), None

    # Get initial top 11 based on score
    top11 = result.nlargest(11, 'score').copy()
    top11.rename(columns={'score': 'Predicted Score'}, inplace=True)
    top11['Predicted Score'] = top11['Predicted Score'].fillna(0).round(0).astype(int)

    #  (ensures role counts)
    def replace_players(top11_df, role_to_limit, max_allowed)
        while (top11_df['final_role'] == role_to_limit).sum() > max_allowed:
            excess_count = (top11_df['final_role'] == role_to_limit).sum() - max_allowed
            to_remove = top11_df[top11_df['final_role'] == role_to_limit].nsmallest(excess_count, 'Predicted Score')

            excluded_ids = top11_df['player_id'].tolist()
            candidates = result[
                (~result['player_id'].isin(excluded_ids)) &
                (result['final_role'] != role_to_limit)
            ].sort_values('score', ascending=False)
            if len(candidates) < excess_count:
                break

            replacements = candidates.head(excess_count).copy()
            replacements = replacements.rename(columns={'score': 'Predicted Score'})
            replacements['Predicted Score'] = replacements['Predicted Score'].fillna(0).round(0).astype(int)

            top11_df = top11_df[~top11_df['player_id'].isin(to_remove['player_id'])]
            top11_df = pd.concat([top11_df, replacements], ignore_index=True)
            top11_df = top11_df.sort_values('Predicted Score', ascending=False).reset_index(drop=True)

        return top11_df

    # Apply max limits
    top11 = replace_players(top11, 'All-rounder', 3)
    top11 = replace_players(top11, 'Batsman', 6)
    top11 = replace_players(top11, 'Bowler', 6)

    # min 1 Wicketkeeper
    if (top11['final_role'] == 'Wicketkeeper').sum() == 0:
        non_wk = top11[top11['final_role'] != 'Wicketkeeper']
        if len(non_wk) > 0:
            lowest_non_wk = non_wk.nsmallest(1, 'Predicted Score')
            excluded_ids = top11['player_id'].tolist()
            wk_candidates = result[
                (~result['player_id'].isin(excluded_ids)) &
                (result['final_role'] == 'Wicketkeeper')
            ].sort_values('score', ascending=False)

            if not wk_candidates.empty:
                wk_replacement = wk_candidates.head(1).copy()
                wk_replacement = wk_replacement.rename(columns={'score': 'Predicted Score'})
                wk_replacement['Predicted Score'] = wk_replacement['Predicted Score'].fillna(0).round(0).astype(int)
                top11 = top11[~top11['player_id'].isin(lowest_non_wk['player_id'])]
                top11 = pd.concat([top11, wk_replacement], ignore_index=True)
                top11 = top11.sort_values('Predicted Score', ascending=False).reset_index(drop=True)

    # min 1 All-rounder
    if (top11['final_role'] == 'All-rounder').sum() == 0:
        non_ar = top11[top11['final_role'] != 'All-rounder']
        if len(non_ar) > 0:
            lowest_non_ar = non_ar.nsmallest(1, 'Predicted Score')
            excluded_ids = top11['player_id'].tolist()
            ar_candidates = result[
                (~result['player_id'].isin(excluded_ids)) &
                (result['final_role'] == 'All-rounder')
            ].sort_values('score', ascending=False)

            if not ar_candidates.empty:
                ar_replacement = ar_candidates.head(1).copy()
                ar_replacement = ar_replacement.rename(columns={'score': 'Predicted Score'})
                ar_replacement['Predicted Score'] = ar_replacement['Predicted Score'].fillna(0).round(0).astype(int)
                top11 = top11[~top11['player_id'].isin(lowest_non_ar['player_id'])]
                top11 = pd.concat([top11, ar_replacement], ignore_index=True)
                top11 = top11.sort_values('Predicted Score', ascending=False).reset_index(drop=True)

    # After replacements, if still less than 11 players, fill with best remaining players
    if len(top11) < 11:
        excluded_ids = top11['player_id'].tolist()
        fillers = result[~result['player_id'].isin(excluded_ids)].sort_values('score', ascending=False).head(11 - len(top11)).copy()
        fillers = fillers.rename(columns={'score': 'Predicted Score'})
        fillers['Predicted Score'] = fillers['Predicted Score'].fillna(0).round(0).astype(int)
        top11 = pd.concat([top11, fillers], ignore_index=True)
        top11 = top11.sort_values('Predicted Score', ascending=False).reset_index(drop=True)

    # Force exactly 11 rows 
    if len(top11) > 11:
        top11 = top11.head(11)
    elif len(top11) < 11:
        blanks = pd.DataFrame({
            'player_id': ['-']*(11 - len(top11)),
            'player_name': ['N/A']*(11 - len(top11)),
            'final_role': ['N/A']*(11 - len(top11)),
            'player_team': ['N/A']*(11 - len(top11)),
            'Predicted Score': [0]*(11 - len(top11))
        })
        top11 = pd.concat([top11, blanks], ignore_index=True)

    # Colors for predicted scores
    scores = top11['Predicted Score'].values
    # n_colors requires integer > 0
    color_count = max(1, len(scores))
    score_colors = n_colors('rgb(0,64,0)', 'rgb(144,238,144)', color_count, colortype='rgb')

    fig = go.Figure(data=[go.Table(
        header=dict(
            values=['<b>Player</b>', '<b>Role</b>', '<b>Team</b>', '<b>Predicted Score</b>'],
            fill_color='#0F172A',
            font=dict(color='white', size=18),
            align='center', height=40
        ),
        cells=dict(
            values=[top11['player_name'], top11['final_role'], top11['player_team'], top11['Predicted Score']],
            fill_color=[
                ["#1E203B"] * 11,
                ['#0F172A'] * 11,
                ['#1E293B'] * 11,
                score_colors
            ],
            font=dict(color='white', size=16),
            align='center', height=38
        )
    )])
    fig.update_layout(height=440, margin=dict(l=0, r=0, t=0, b=0))

    return f"Top 11 Fantasy Team for {match_date_str}", gr.update(choices=selected_players), fig

#  Player Stats & 3-Plot Trends 
def show_player_stats(player_name, match_date_str):
    """
    Returns: stats_text (md), fig1 (fantasy trend), fig2 (main), fig3 (secondary)
    """
    if not player_name:
        return "Select a player.", None, None, None

    try:
        match_date = pd.to_datetime(match_date_str)
    except Exception:
        return "Invalid date format.", None, None, None

    df_player = df1[(df1['player_name'] == player_name) & (df1['start_date'] < match_date)].sort_values('start_date')

    if df_player.empty:
        return "No data for this player.", None, None, None

    role = df_player['final_role'].mode()[0] if not df_player['final_role'].mode().empty else "Batsman"
    last12 = df_player.tail(12)
    x = list(range(1, len(last12) + 1))

    # Fantasy score trend
    fig1 = go.Figure(go.Scatter(x=x, y=last12['fantasy_score_total'], mode='lines+markers',
                                line=dict(color='#3B82F6', width=3)))
    fig1.update_layout(template='plotly_dark', title='Fantasy Score Trend', xaxis_title='Last Matches', yaxis_title='Fantasy Score')

    if role in ['Batsman', 'Wicketkeeper']:
        fig2 = go.Figure(go.Bar(x=x, y=last12['runs_scored'], marker_color='#10B981'))
        fig2.update_layout(template='plotly_dark', title='Runs Trend', xaxis_title='Last Matches', yaxis_title='Runs')

        fig3 = go.Figure()
        fig3.add_bar(x=x, y=last12['fours_scored'], name='4s', marker_color='orange')
        fig3.add_bar(x=x, y=last12['sixes_scored'], name='6s', marker_color='red')
        fig3.update_layout(template='plotly_dark', title='Fours & Sixes', xaxis_title='Last Matches', yaxis_title='Count', barmode='group')

    elif role == 'All-rounder':
        fig2 = go.Figure(go.Bar(x=x, y=last12['runs_scored'], marker_color='#10B981'))
        fig2.update_layout(template='plotly_dark', title='Runs Trend', xaxis_title='Last Matches', yaxis_title='Runs')

        fig3 = go.Figure(go.Bar(x=x, y=last12['wickets_taken'], marker_color='#1D4ED8'))
        fig3.update_layout(template='plotly_dark', title='Wickets Trend', xaxis_title='Last Matches', yaxis_title='Wickets')

    else:  # Bowler or unknown
        fig2 = go.Figure(go.Bar(x=x, y=last12['wickets_taken'], marker_color='#1D4ED8'))
        fig2.update_layout(template='plotly_dark', title='Wickets Trend', xaxis_title='Last Matches', yaxis_title='Wickets')

        # compute economy safely
        def safe_econ(r):
            balls = r['balls_bowled'] if (pd.notna(r['balls_bowled']) and r['balls_bowled'] > 0) else 1
            runs = r['runs_conceded'] if pd.notna(r['runs_conceded']) else 0
            return runs / (balls / 6)

        economy = last12.apply(safe_econ, axis=1)
        fig3 = go.Figure(go.Scatter(x=x, y=economy, mode='lines+markers', line=dict(color='purple', width=3)))
        fig3.update_layout(template='plotly_dark', title='Economy Rate', xaxis_title='Last Matches', yaxis_title='Economy')

    stats_text = f"### {player_name} — {role}\n**Fantasy Avg (last5): {round(df_player.tail(5)['fantasy_score_total'].mean(), 1)}**"

    return stats_text, fig1, fig2, fig3

# Career Yearly Plots 

def plot_career_yearly_stats(player_name, dfx):
    """
    Returns 9 figures:
    (batting_runs, batting_avg, batting_strike, batting_50s, batting_100s,
     bowling_wickets, bowling_economy, bowling_strike, bowling_5fers)
    """
    dfx_player = dfx[dfx['player_name'] == player_name].copy()
    if dfx_player.empty:
        empty_fig = go.Figure()
        empty_fig.update_layout(template='plotly_dark', title="No Career Data")
        return tuple([empty_fig] * 9)

    dfx_player['year'] = dfx_player['start_date'].dt.year
    role = dfx_player['final_role'].mode()[0] if not dfx_player['final_role'].empty else "Unknown"

    # Batting plots 
    batting = dfx_player[dfx_player['final_role'].isin(['Batsman', 'Wicketkeeper', 'All-rounder'])]
    if batting.empty:
        batting_runs_fig = batting_avg_fig = batting_strike_fig = batting_50s_fig = batting_100s_fig = go.Figure()
        for fig in [batting_runs_fig, batting_avg_fig, batting_strike_fig, batting_50s_fig, batting_100s_fig]:
            fig.update_layout(template='plotly_dark', title="No Batting Data")
    else:
        batting_yearly = batting.groupby('year').agg({
            'runs_scored': 'sum',
            'balls_faced': 'sum',
            'start_date': 'count',
        }).rename(columns={'start_date': 'matches'}).reset_index()

        batting_yearly['strike_rate'] = batting_yearly.apply(
            lambda row: (row['runs_scored'] / row['balls_faced'] * 100) if row['balls_faced'] > 0 else 0, axis=1)
        batting_yearly['batting_avg'] = batting_yearly.apply(
            lambda row: (row['runs_scored'] / row['matches']) if row['matches'] > 0 else 0, axis=1)

        fifties = batting[(batting['runs_scored'] >= 50) & (batting['runs_scored'] < 100)]
        hundreds = batting[batting['runs_scored'] >= 100]

        fifties_yearly = fifties.groupby('year').size().reset_index(name='50s')
        hundreds_yearly = hundreds.groupby('year').size().reset_index(name='100s')

        batting_yearly = batting_yearly.merge(fifties_yearly, on='year', how='left').merge(hundreds_yearly, on='year', how='left')
        batting_yearly['50s'] = batting_yearly['50s'].fillna(0)
        batting_yearly['100s'] = batting_yearly['100s'].fillna(0)

        batting_runs_fig = go.Figure(go.Bar(x=batting_yearly['year'], y=batting_yearly['runs_scored'], marker_color='#10B981'))
        batting_runs_fig.update_layout(template='plotly_dark', title='Runs Per Year', yaxis_title='Runs')

        batting_avg_fig = go.Figure(go.Scatter(x=batting_yearly['year'], y=batting_yearly['batting_avg'], mode='lines+markers', line=dict(color='yellow')))
        batting_avg_fig.update_layout(template='plotly_dark', title='Batting Average Per Year', yaxis_title='Batting Average')

        batting_strike_fig = go.Figure(go.Scatter(x=batting_yearly['year'], y=batting_yearly['strike_rate'], mode='lines+markers', line=dict(color='orange')))
        batting_strike_fig.update_layout(template='plotly_dark', title='Strike Rate Per Year', yaxis_title='Strike Rate')

        batting_50s_fig = go.Figure(go.Bar(x=batting_yearly['year'], y=batting_yearly['50s'], marker_color='lightblue'))
        batting_50s_fig.update_layout(template='plotly_dark', title='50s Per Year', yaxis_title='50s')

        batting_100s_fig = go.Figure(go.Bar(x=batting_yearly['year'], y=batting_yearly['100s'], marker_color='lightgreen'))
        batting_100s_fig.update_layout(template='plotly_dark', title='100s Per Year', yaxis_title='100s')

    # Bowling plots 
    bowling = dfx_player[dfx_player['final_role'].isin(['Bowler', 'All-rounder'])]
    if bowling.empty:
        bowling_wickets_fig = bowling_economy_fig = bowling_strike_fig = bowling_5fers_fig = go.Figure()
        for fig in [bowling_wickets_fig, bowling_economy_fig, bowling_strike_fig, bowling_5fers_fig]:
            fig.update_layout(template='plotly_dark', title="No Bowling Data")
    else:
        bowling_yearly = bowling.groupby('year').agg({
            'wickets_taken': 'sum',
            'runs_conceded': 'sum',
            'balls_bowled': 'sum',
        }).reset_index()

        bowling_yearly['economy'] = bowling_yearly.apply(
            lambda row: (row['runs_conceded'] / (row['balls_bowled'] / 6)) if row['balls_bowled'] > 0 else 0, axis=1)
        bowling_yearly['strike_rate'] = bowling_yearly.apply(
            lambda row: (row['balls_bowled'] / row['wickets_taken']) if row['wickets_taken'] > 0 else 0, axis=1)

        five_fers = bowling[bowling['wickets_taken'] >= 5]
        five_fers_yearly = five_fers.groupby('year').size().reset_index(name='5fers')
        bowling_yearly = bowling_yearly.merge(five_fers_yearly, on='year', how='left')
        bowling_yearly['5fers'] = bowling_yearly['5fers'].fillna(0)

        bowling_wickets_fig = go.Figure(go.Bar(x=bowling_yearly['year'], y=bowling_yearly['wickets_taken'], marker_color='#3B82F6'))
        bowling_wickets_fig.update_layout(template='plotly_dark', title='Wickets Per Year', yaxis_title='Wickets')

        bowling_economy_fig = go.Figure(go.Scatter(x=bowling_yearly['year'], y=bowling_yearly['economy'], mode='lines+markers', line=dict(color='orange')))
        bowling_economy_fig.update_layout(template='plotly_dark', title='Economy Rate Per Year', yaxis_title='Economy')

        bowling_strike_fig = go.Figure(go.Scatter(x=bowling_yearly['year'], y=bowling_yearly['strike_rate'], mode='lines+markers', line=dict(color='yellow')))
        bowling_strike_fig.update_layout(template='plotly_dark', title='Bowling Strike Rate Per Year', yaxis_title='Strike Rate')

        bowling_5fers_fig = go.Figure(go.Bar(x=bowling_yearly['year'], y=bowling_yearly['5fers'], marker_color='lightgreen'))
        bowling_5fers_fig.update_layout(template='plotly_dark', title='5-fers Per Year', yaxis_title='5-fers')

    # Return plots based on role:
    if role in ['Batsman', 'Wicketkeeper']:
        # Only batting plots, set bowling plots empty
        return batting_runs_fig, batting_avg_fig, batting_strike_fig, batting_50s_fig, batting_100s_fig, \
               go.Figure().update_layout(template='plotly_dark', title="No Bowling Data"), \
               go.Figure().update_layout(template='plotly_dark', title="No Bowling Data"), \
               go.Figure().update_layout(template='plotly_dark', title="No Bowling Data"), \
               go.Figure().update_layout(template='plotly_dark', title="No Bowling Data")

    elif role == 'Bowler':
        # Only bowling plots, set batting plots empty
        empty_fig = go.Figure()
        empty_fig.update_layout(template='plotly_dark', title="No Batting Data")
        return empty_fig, empty_fig, empty_fig, empty_fig, empty_fig, bowling_wickets_fig, bowling_economy_fig, bowling_strike_fig, bowling_5fers_fig

    elif role == 'All-rounder':
        # Show all plots
        return batting_runs_fig, batting_avg_fig, batting_strike_fig, batting_50s_fig, batting_100s_fig, \
               bowling_wickets_fig, bowling_economy_fig, bowling_strike_fig, bowling_5fers_fig

    else:
        # Unknown role, return empty for all
        empty_fig = go.Figure()
        empty_fig.update_layout(template='plotly_dark', title="No Data")
        return tuple([empty_fig] * 9)

#  Wrapper to be used by UI
def show_career_stats_and_plots(player_name, dfx):
    if not player_name:
        empty_fig = go.Figure()
        empty_fig.update_layout(template='plotly_dark', title="No Player Selected")
        return "Select a player.", empty_fig, empty_fig, empty_fig, empty_fig, empty_fig, empty_fig, empty_fig, empty_fig, empty_fig

    stats_md = get_career_stats_for_player(player_name, dfx)
    (career_batting_runs, career_batting_avg, career_batting_strike, career_batting_50s, career_batting_100s,
     career_bowling_wickets, career_bowling_economy, career_bowling_strike, career_bowling_5fers) = plot_career_yearly_stats(player_name, dfx)

    return (stats_md, career_batting_runs, career_batting_avg, career_batting_strike, career_batting_50s,
            career_batting_100s, career_bowling_wickets, career_bowling_economy, career_bowling_strike, career_bowling_5fers)

# Gradio UI
with gr.Blocks(css=".gradio-container {background-color: #0F172A; color: white;}") as app:
    gr.Markdown("<h1 style='text-align:center; color:#38BDF8;'> Breaking 11 — Fantasy Dream Team Predictor</h1>")

    with gr.Row():
        team_a = gr.Dropdown(choices=sorted(df1['player_team_str'].unique()), label="Select Team A")
        team_b = gr.Dropdown(choices=sorted(df1['player_team_str'].unique()), label="Select Team B")

    player_dd = gr.Dropdown(choices=[], label="Select Players from Team A & B", multiselect=True, max_choices=26)

    date_input = gr.Textbox(label="Match Date (YYYY-MM-DD)", value=str(datetime.now().date()))

    # single Predict Top 11 button (wired correctly below)
    btn = gr.Button(" Predict Top 11")
    status = gr.Markdown()
    top11_chart = gr.Plot(label="Predicted XI Visualization")

    # Tabs for player stats and career stats
    with gr.Tabs():
        with gr.TabItem("Player Stats & Trends"):
            sel_player_stats = gr.Dropdown(choices=[], label="View Player Stats & Trends")
            player_stats = gr.Markdown()
            plot_fantasy = gr.Plot()
            plot_main = gr.Plot()
            plot_secondary = gr.Plot()

        with gr.TabItem("Career Stats"):
            sel_player_career = gr.Dropdown(choices=[], label="View Career Stats for Selected Player")
            career_stats_md = gr.Markdown()

            # Batting plots (5 separate)
            career_batting_runs = gr.Plot(label="Runs Per Year")
            career_batting_avg = gr.Plot(label="Batting Average Per Year")
            career_batting_strike = gr.Plot(label="Strike Rate Per Year")
            career_batting_50s = gr.Plot(label="50s Per Year")
            career_batting_100s = gr.Plot(label="100s Per Year")

            # Bowling plots (4 separate)
            career_bowling_wickets = gr.Plot(label="Wickets Per Year")
            career_bowling_economy = gr.Plot(label="Economy Rate Per Year")
            career_bowling_strike = gr.Plot(label="Bowling Strike Rate Per Year")
            career_bowling_5fers = gr.Plot(label="5-Fers Per Year")

    # Update player dropdown choices when teams are selected
    def update_player_choices(t1, t2):
        if t1 and t2:
            players = df1[df1['player_team_str'].isin([t1, t2])]['player_name'].unique()
            return gr.update(choices=sorted(players.tolist()), value=[])
        return gr.update(choices=[], value=[])

    team_a.change(update_player_choices, inputs=[team_a, team_b], outputs=player_dd)
    team_b.change(update_player_choices, inputs=[team_a, team_b], outputs=player_dd)

    # Update player stats dropdown when player list changes
    def update_stats_dropdown(players):
        choices = sorted(players) if players else []
        return gr.update(choices=choices, value=None), gr.update(choices=choices, value=None)

    player_dd.change(update_stats_dropdown, inputs=player_dd, outputs=[sel_player_stats, sel_player_career])

    btn.click(fn=predict_top11, inputs=[player_dd, date_input], outputs=[status, player_dd, top11_chart])
    sel_player_stats.change(show_player_stats, inputs=[sel_player_stats, date_input],
                            outputs=[player_stats, plot_fantasy, plot_main, plot_secondary])

    def show_career_stats_wrapper(player_name):
        global dfx
        # fallback to df1 if dfx is None
        use_df = dfx if (dfx is not None and not dfx.empty) else df1
        return show_career_stats_and_plots(player_name, use_df)

    sel_player_career.change(
        show_career_stats_wrapper,
        inputs=[sel_player_career],
        outputs=[career_stats_md, career_batting_runs, career_batting_avg, career_batting_strike,
                 career_batting_50s, career_batting_100s, career_bowling_wickets, career_bowling_economy,
                 career_bowling_strike, career_bowling_5fers]
    )
app.launch()

* Running on local URL:  http://127.0.0.1:7914
* To create a public link, set `share=True` in `launch()`.